apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bbx-dev-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: bbx-dev-secret
  data:
  - secretKey: gitlab-token
    remoteRef:
      key: bbx-dev-secret
      property: gitlab-token


