apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-cred
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: ghcr-cred
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .auth | toString }}"
    creationPolicy: Owner
  data:
  - secretKey: auth
    remoteRef:
      key: infra-secret
      property: dockerconfigjson

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: newrelic-license-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: newrelic-license-key
  data:
  - secretKey: ingestion.key
    remoteRef:
      key: infra-secret
      property: newrelic_license_key


---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bbx-dev-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: git-indexer-secret
  data:
  - secretKey: gitlab-token
    remoteRef:
      key: bbx-dev-secret
      property: gitlab-token
  - secretKey: postgres-password
    remoteRef:
      key: bbx-dev-secret
      property: postgres-password
  - secretKey: postgres-replication-password
    remoteRef:
      key: bbx-dev-secret
      property: postgres-replication-password
  - secretKey: app-db-url
    remoteRef:
      key: bbx-dev-secret
      property: app-db-url
  - secretKey: app-pg-dbname
    remoteRef:
      key: bbx-dev-secret
      property: app-pg-dbname
  - secretKey: app-pg-user
    remoteRef:
      key: bbx-dev-secret
      property: app-pg-user
  - secretKey: app-pg-password
    remoteRef:
      key: bbx-dev-secret
      property: app-pg-password
