apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- repo-secret.yaml
- ../../base
- ../../optional/github-registry-cred.yaml
# - ../../namespaces/vinobank-dev
- ../../namespaces/bbx-dev
