apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base
  - ../../../../infra/controllers/optional/cert-manager.yaml
  - ../../../../infra/controllers/optional/nfs-subdir-external-provisioner
  - ../../../../infra/controllers/optional/longhorn
  - ../../../../infra/controllers/optional/cnpg
  - ../../../../infra/controllers/optional/nats.yaml

patches:
  - path: patch-nfs-server.yaml
