apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gcp-secret-store.yaml
- traefik-dashboard-ingressroute.yaml
- letsencrypt-cluster-issuer.yaml
- weave-gitops.yaml
- whoami.yaml

