apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  type: oci
  interval: 24h
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 24h
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.38
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
      interval: 12h
  # https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/values.yaml
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    adminUser:
      create: true
  valuesFrom:
    - kind: Secret
      name: gitops-credential
      valuesKey: username
      targetPath: adminUser.username
    - kind: Secret
      name: gitops-credential
      valuesKey: password
      targetPath: adminUser.passwordHash

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitops-credential
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: gitops-credential
  data:
    - secretKey: username
      remoteRef:
        key: infra-secret
        property: gitops_username
    - secretKey: password
      remoteRef:
        key: infra-secret
        property: gitops_password
---
kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: gitops-dashboard
  namespace: flux-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      priority: 10
      services:
        - kind: Service
          name: weave-gitops
          port: 9001
