# for each deployment
# we'll setup:
#   one GitRepository pointing to the git branch
#   one Kustomization using the above GitRepository

# dev env setup
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vinobank-repo-dev
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/vino9net/vinobank-gitops
  ref:
    branch: develop
  secretRef:
    name: vinobank-repo-token
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-infra-test
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: vinobank-repo-dev
  path: ./infra-test/env/dev
  wait: true
  prune: true
