apiVersion: v1
kind: Namespace
metadata:
  name: infra

---
apiVersion: v1
kind: Secret
metadata:
  name: gcpsm-secret
  namespace: infra
  labels:
    type: gcpsm
type: Opaque
stringData:
  secret-access-credentials: |-
    the content of GCP key json file here
