apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../optional/cert-manager.yaml
- ../../optional/nfs-subdir-external-provisioner
- ../../optional/longhorn
- ../../optional/kubegres

