apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
      - name: nfs-client-provisioner
        env:
        - name: NFS_SERVER
          value: host.docker.internal
        - name: NFS_PATH
          value: /share
      volumes:
      - name: nfs-client-root
        nfs:
          server: host.docker.internal
          path: /share
