apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/knative/serving/releases/download/knative-v1.14.2/serving-crds.yaml
  - https://github.com/knative/eventing/releases/download/knative-v1.14.7/eventing-crds.yaml
