apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/knative/eventing/releases/download/knative-v1.18.2/eventing-core.yaml
  - https://github.com/knative/eventing/releases/download/knative-v1.18.2/in-memory-channel.yaml
  - https://github.com/knative/eventing/releases/download/knative-v1.18.2/mt-channel-broker.yaml
  - broker-config.yaml
