apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/knative/eventing/releases/download/knative-v1.18.1/eventing-core.yaml
  - https://github.com/knative/eventing/releases/download/knative-v1.18.1/in-memory-channel.yaml
  - https://github.com/knative/eventing/releases/download/knative-v1.18.1/mt-channel-broker.yaml
