apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: infra
spec:
  interval: 24h
  url: https://charts.external-secrets.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: infra
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "0.8.3"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 12h
  values:
    installCRDs: true
