apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/knative/serving/releases/download/knative-v1.18.1/serving-core.yaml
  - https://github.com/knative/net-contour/releases/download/knative-v1.18.0/contour.yaml
  - https://github.com/knative/net-contour/releases/download/knative-v1.18.0/net-contour.yaml
  - https://github.com/knative/serving/releases/download/knative-v1.18.1/serving-default-domain.yaml
patches:
  - target:
      kind: ConfigMap
      name: config-network
      namespace: knative-serving
    patch: |-
      - op: replace
        path: /data/ingress-class
        value: contour.ingress.networking.knative.dev
