apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: team-ssh-keys
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: vinobank-repo-token
  data:
  - secretKey: username
    remoteRef:
      key: vinobank-gitops-token
      property: username
  - secretKey: password
    remoteRef:
      key: vinobank-gitops-token
      property: password
