apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gitops-repo-tokens.yaml
- ../../base
- ../../optional/letsencrypt-cluster-issuer.yaml
- ../../optional/newrelic.yaml
- ../../optional/github-registry-cred.yaml
- ../../namespaces/vinobank-dev
- ../../namespaces/vinobank
- ../../namespaces/bbx-dev
