apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: team-ssh-keys
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: vinobank-repo-key
  data:
  - secretKey: identity
    remoteRef:
      key: team-ssh-keys
      property: vinobank.identity
  - secretKey: identity.pub
    remoteRef:
      key: team-ssh-keys
      property: vinobank.identity.pub
  - secretKey: known_hosts
    remoteRef:
      key: team-ssh-keys
      property: vinobank.known_hosts
