apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/longhorn/longhorn/v1.4.2/deploy/longhorn.yaml
- storage-class.yaml
- longhorn-dashboard-ingressroute.yaml
