apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: infra
spec:
  interval: 72h
  url: https://charts.jetstack.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: infra
spec:
  interval: 24h
  chart:
    spec:
      chart: cert-manager
      version: "1.13.3"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: infra
      interval: 12h
  values:
    installCRDs: true

