apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nats
  namespace: infra
spec:
  interval: 24h
  url: https://nats-io.github.io/k8s/helm/charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: infra
spec:
  interval: 30m
  chart:
    spec:
      chart: nats
      version: "0.19.14"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: infra
      interval: 12h
  values:
    cluster:
      enabled: false
      replicas: 1

    nats:
      externalAccess: true
      advertise: false

      jetstream:
        enabled: true

        memStorage:
          enabled: true
          size: 512Mi

        fileStorage:
          enabled: false

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nack
  namespace: infra
spec:
  interval: 30m
  chart:
    spec:
      chart: nack
      version: "0.21.0"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: infra
      interval: 12h
  values:
    jetstream:
      nats:
        url: nats://nats:4222
