apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redis-operator
  namespace: infra
spec:
  interval: 24h
  url: https://spotahome.github.io/redis-operator

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: infra
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-operator
      version: "3.2.8"
      sourceRef:
        kind: HelmRepository
        name: redis-operator
        namespace: infra
      interval: 12h
