apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redis-operator
  namespace: infra
spec:
  interval: 72h
  url: https://ot-container-kit.github.io/helm-charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: infra
spec:
  interval: 24h
  chart:
    spec:
      chart: redis-operator
      version: "0.21.0"
      sourceRef:
        kind: HelmRepository
        name: redis-operator
        namespace: infra
      interval: 12h
