apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vinobank-prod-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: aws-credential
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: vinobank-dev-secret
        property: aws_access_key_id
    - secretKey: aws_secret_access_key
      remoteRef:
        key: vinobank-dev-secret
        property: aws_secret_access_key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newrelic-license-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: newrelic-license-key
  data:
    - secretKey: ingestion.key
      remoteRef:
        key: infra-secret
        property: newrelic_license_key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-cred
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: ghcr-cred
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "auth": "{{ printf "oauth2:%s" .ghcr_io_token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: ghcr_io_token
      remoteRef:
        key: infra-secret
        property: ghcr_io_token
