apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/knative/serving/releases/download/knative-v1.16.0/serving-core.yaml
  - https://github.com/knative/net-kourier/releases/download/knative-v1.16.0/kourier.yaml
  - https://github.com/knative/serving/releases/download/knative-v1.16.0/serving-default-domain.yaml
  # the release yaml contains syntax error, use local patched version until it is fixed
  # https://github.com/knative/eventing/issues/8412
  # - https://github.com/knative/eventing/releases/download/knative-v1.16.3/eventing-core.yaml
  - eventing-core-v1.16.3-patched.yaml
  - https://github.com/knative/eventing/releases/download/knative-v1.16.3/in-memory-channel.yaml
  - https://github.com/knative/eventing/releases/download/knative-v1.16.3/mt-channel-broker.yaml
patches:
  - target:
      kind: ConfigMap
      name: config-network
      namespace: knative-serving
    patch: |-
      - op: replace
        path: /data/ingress-class
        value: kourier.ingress.networking.knative.dev
