apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-cred
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: ghcr-cred-2
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .mysecret | toString }}"
    creationPolicy: Owner
  data:
  - secretKey: mysecret
    remoteRef:
      key: dockerconfigjson
