apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vinobank-repo-token
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: vinobank-repo-token
  data:
    - secretKey: username
      remoteRef:
        key: vinobank-gitops-token
        property: username
    - secretKey: password
      remoteRef:
        key: vinobank-gitops-token
        property: password
