apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: infra
spec:
  acme:
    email: guru.lin@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # use staging server for experimentation and troubleshooting
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer
    solvers:
      - dns01:
          cnameStrategy: Follow
          cloudflare:
            emailSecretRef:
              name: dns-credential
              key: cloudflare-email
            apiTokenSecretRef:
              name: dns-credential
              key: cloudflare-api-token
        selector:
          dnsZones:
            - "app.vino9.net"

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dns-credential
  namespace: infra
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: dns-credential
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: infra-secret
        property: cloudflare_api_token
    - secretKey: cloudflare-email
      remoteRef:
        key: infra-secret
        property: cloudflare_email
