apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: newrelic-bundle
  namespace: infra
spec:
  interval: 72h
  url: https://helm-charts.newrelic.com

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nri-bundle
  namespace: infra
spec:
  interval: 24h
  chart:
    spec:
      chart: nri-bundle
      version: "5.0.56"
      sourceRef:
        kind: HelmRepository
        name: newrelic-bundle
        namespace: infra
      interval: 12h
  values:
    global:
      # cluster name will be patched by kustomize during deployment
      cluster: rancher-desktop
      lowDataMode: true
    newrelic-infrastructure:
      privileged: true
    ksm:
      enabled: true
      prometheusScrape: false
    kubeEvents:
      # disable to lower data sent to NR
      enabled: false
    newrelic-prometheus-agent:
      # disable to lower data sent to NR
      enabled: false
    newrelic-logging:
      enabled: true
      fluentBit:
        criEnabled: true
  valuesFrom:
  - kind: Secret
    name: newrelic-license-key
    valuesKey: ingestion.key
    targetPath: global.licenseKey

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: newrelic-license-key
  namespace: infra
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: newrelic-license-key
  data:
  - secretKey: ingestion.key
    remoteRef:
      key: infra-secret
      property: newrelic_license_key
