apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vinobank-repo-dev
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: develop
  secretRef:
    name: vinobank-repo-key
  url: ssh://git@github.com/vino9org/vinobank-gitops

